// SPDX-License-Identifier: MIT
#include "dc_ui.h"

// Generated by target_add_binary_data() from dc_ui_app.html.gz.
extern const uint8_t dc_ui_app_html_gz_start[]
    asm("_binary_dc_ui_app_html_gz_start");
extern const uint8_t dc_ui_app_html_gz_end[]
    asm("_binary_dc_ui_app_html_gz_end");

dc_ui_asset_t dc_ui_spa_asset(void)
{
    return (dc_ui_asset_t) {
        .data = dc_ui_app_html_gz_start,
        .len = (size_t)(dc_ui_app_html_gz_end - dc_ui_app_html_gz_start),
        .content_type = "text/html; charset=utf-8",
        .content_encoding = "gzip",
    };
}
